#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'competition','console_scripts','drone_test'
__requires__ = 'competition'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('competition', 'console_scripts', 'drone_test')()
    )
